global:
  affinity:
    key: kubernetes.io/hostname
    values:
      - share-61
  affinityEnabled: true
  commonAnnotations: {}
  commonLabels: {}
  component: ""
  imagePullPolicy: IfNotPresent
  imageRegistry: ""             
  inst_id: ""
  engine_tag: "vim"              
  space_inst: ""
  resourcesEnabled: true
  tolerations: []

persistence:
  class: host
  enabled: false
  nfs_server: ""
  path: /data/k8s
  pv_size: 51Gi
  pvc_size: 50Gi

service:
  fixed: true
  ipMid: 251
  ipPost: 1
  ipPre: 10.99.

vflengine:
  host:
    name: "host"
    port: 50051
    ui_port: 5014
  guest:
    name: "guest"
    port: 50052
    ui_port: 5013

  affinity:
    key: ""
    values: []

  enabled: true
  extraAnnotations: {}
  extraEnvs: {}
  extraLabels: {}

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  extraVolumeMounts:
    cache: /mnt
    data: /data

  image:
    registry: ""               
    repository: "10.12.0.78:5000/jewel-release/vflengine"
    tag: "4.0.0"

  name: vflengine
  replicaCount: 1
  resources: {}
  tolerations: []
